
# version: '3'

# services:
#   app:
#     build: .

#     depends_on:
#       - db
#     container_name: web
#     environment:
#       - POSTGRES_ENGINE=django.db.backends.postgresql_psycopg2
#       - POSTGRES_DB=strategy_agency
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=123
#       - POSTGRES_HOST=db
#       - POSTGRES_PORT=5432
#     ports:
#       - 8000:8000
  
#   db:
#     image: postgres:9.6
#     container_name: db
#     environment:
#      - POSTGRES_DB=strategy_agency
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=123
#      - "POSTGRES_HOST_AUTH_METHOD=trust"
     
#     # ports:
#     #   - 5434:5434
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
    

  
version: "3.8"

services:
  db:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_DB=strategy_agency
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - ./data:/var/lib/postgresql/data
  
  web:
    build: .
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
    pgdb:
    web:











