# Generated by Django 4.1.2 on 2023-04-06 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.FloatField(blank=True, null=True)),
                ('B', models.FloatField(blank=True, null=True)),
                ('C', models.FloatField(blank=True, null=True)),
                ('D', models.FloatField(blank=True, null=True)),
                ('E', models.FloatField(blank=True, null=True)),
                ('F', models.FloatField(blank=True, null=True)),
                ('G', models.FloatField(blank=True, null=True)),
                ('H', models.FloatField(blank=True, null=True)),
                ('I', models.FloatField(blank=True, null=True)),
                ('J', models.FloatField(blank=True, null=True)),
                ('K', models.FloatField(blank=True, null=True)),
                ('L', models.FloatField(blank=True, null=True)),
                ('M', models.FloatField(blank=True, null=True)),
                ('N', models.FloatField(blank=True, null=True)),
                ('O', models.FloatField(blank=True, null=True)),
                ('P', models.FloatField(blank=True, null=True)),
                ('Q', models.FloatField(blank=True, null=True)),
                ('R', models.FloatField(blank=True, null=True)),
                ('S', models.FloatField(blank=True, null=True)),
                ('T', models.FloatField(blank=True, null=True)),
                ('U', models.FloatField(blank=True, null=True)),
                ('V', models.FloatField(blank=True, null=True)),
                ('W', models.FloatField(blank=True, null=True)),
                ('X', models.FloatField(blank=True, null=True)),
                ('Y', models.FloatField(blank=True, null=True)),
                ('Z', models.FloatField(blank=True, null=True)),
                ('AA', models.FloatField(blank=True, null=True)),
                ('AB', models.FloatField(blank=True, null=True)),
                ('AC', models.FloatField(blank=True, null=True)),
                ('AD', models.FloatField(blank=True, null=True)),
                ('AE', models.FloatField(blank=True, null=True)),
                ('AF', models.FloatField(blank=True, null=True)),
                ('AG', models.FloatField(blank=True, null=True)),
                ('AH', models.FloatField(blank=True, null=True)),
                ('AI', models.FloatField(blank=True, null=True)),
                ('AJ', models.FloatField(blank=True, null=True)),
                ('AK', models.FloatField(blank=True, null=True)),
                ('AL', models.FloatField(blank=True, null=True)),
                ('AM', models.FloatField(blank=True, null=True)),
                ('AN', models.FloatField(blank=True, null=True)),
                ('AO', models.FloatField(blank=True, null=True)),
                ('AP', models.FloatField(blank=True, null=True)),
                ('AQ', models.FloatField(blank=True, null=True)),
                ('AR', models.FloatField(blank=True, null=True)),
                ('AS', models.FloatField(blank=True, null=True)),
                ('AT', models.FloatField(blank=True, null=True)),
                ('AU', models.FloatField(blank=True, null=True)),
                ('AV', models.FloatField(blank=True, null=True)),
                ('AW', models.FloatField(blank=True, null=True)),
                ('AX', models.FloatField(blank=True, null=True)),
                ('AY', models.FloatField(blank=True, null=True)),
                ('AZ', models.FloatField(blank=True, null=True)),
                ('BA', models.FloatField(blank=True, null=True)),
                ('BB', models.FloatField(blank=True, null=True)),
                ('BC', models.FloatField(blank=True, null=True)),
                ('BD', models.FloatField(blank=True, null=True)),
                ('BE', models.FloatField(blank=True, null=True)),
                ('BF', models.FloatField(blank=True, null=True)),
                ('BG', models.FloatField(blank=True, null=True)),
                ('BH', models.FloatField(blank=True, null=True)),
                ('BI', models.FloatField(blank=True, null=True)),
                ('BJ', models.FloatField(blank=True, null=True)),
                ('BK', models.FloatField(blank=True, null=True)),
                ('BL', models.FloatField(blank=True, null=True)),
                ('BM', models.FloatField(blank=True, null=True)),
                ('BN', models.FloatField(blank=True, null=True)),
                ('BO', models.FloatField(blank=True, null=True)),
                ('BP', models.FloatField(blank=True, null=True)),
                ('BQ', models.FloatField(blank=True, null=True)),
                ('BR', models.FloatField(blank=True, null=True)),
                ('BS', models.FloatField(blank=True, null=True)),
                ('BT', models.FloatField(blank=True, null=True)),
                ('BU', models.FloatField(blank=True, null=True)),
                ('BV', models.FloatField(blank=True, null=True)),
                ('BW', models.FloatField(blank=True, null=True)),
                ('BX', models.FloatField(blank=True, null=True)),
                ('BY', models.FloatField(blank=True, null=True)),
                ('BZ', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Матрица',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_product', models.CharField(max_length=50)),
                ('product_name', models.TextField(verbose_name='Продукт')),
                ('skp', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SkpValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Значение Скп',
                'verbose_name_plural': 'Значения Скп',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='X_and_C_for_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('skp', models.CharField(max_length=50)),
                ('all_used_resources', models.FloatField(blank=True, null=True)),
                ('final_demand', models.FloatField(blank=True, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.year')),
            ],
            options={
                'verbose_name': 'X-C',
                'verbose_name_plural': 'X-C',
            },
        ),
        migrations.CreateModel(
            name='Import_export_for_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('skp', models.CharField(max_length=50)),
                ('_import', models.FloatField(blank=True, null=True)),
                ('export', models.FloatField(blank=True, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.year')),
            ],
            options={
                'verbose_name': 'Импорт-Экспорт',
                'verbose_name_plural': 'Импорт-Экспорт',
            },
        ),
        migrations.CreateModel(
            name='Gdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('economic_activity', models.CharField(max_length=50)),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.year')),
            ],
            options={
                'verbose_name': 'ВВП',
                'verbose_name_plural': 'ВВП',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True)),
                ('duty', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='module.country')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='module.product')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.year')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
            },
        ),
    ]
