# Generated by Django 4.1.2 on 2023-03-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0023_alter_product_code_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkpValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Значение Скп',
                'verbose_name_plural': 'Значения Скп',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterModelOptions(
            name='gdp',
            options={'verbose_name': 'ВВП', 'verbose_name_plural': 'ВВП'},
        ),
        migrations.AlterModelOptions(
            name='import_export_for_db',
            options={'verbose_name': 'Импорт-Экспорт', 'verbose_name_plural': 'Импорт-Экспорт'},
        ),
        migrations.AlterModelOptions(
            name='matrix',
            options={'verbose_name_plural': 'Матрица'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='x_and_c_for_db',
            options={'verbose_name': 'X-C', 'verbose_name_plural': 'X-C'},
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.TextField(verbose_name='Продукт'),
        ),
    ]
